### ISSUE TITLE
Get all folders of a mailbox

### ISSUE THREAD

**Issue by Robinouh** [Garethp/php-ews#120]
Hi,

I would like to know if I can get all folders of a mailbox ?

![sans titre](https://user-images.githubusercontent.com/35724895/36248865-2a17832e-1239-11e8-8170-c1c64134d7e8.png)

For example, as shown in the image above, the "Boîte de réception", "Boîte d'envoi", "Brouillons", "Courriers indésirables", "Éléments envoyés" and "Éléments supprimés" folders should be retrieved.

Is it possible?

I imagine a code that would look like this:

```
$api = MailAPI::withUsernameAndPassword($server, $user, $password);

$folders = $api->getFolders();

foreach($folders as $folder)
{
    echo $folder->getDisplayName() . "<br>";
}
```

Obviously, the function "getFolders" does not exist but there is maybe a function to do that?

**Comment by Garethp** [comment]
What you can do is you can get children folders, as long as you know what folder you want to start with. It will however, most likely show you more folders than the user can see. In order to get all children folders for message for example, you can do

```php
$folders = $api->getChildrenFolders(\garethp\ews\API\Type\DistinguishedFolderIdNameType::MESSAGE_ROOT);
```

Note that most of those folders are what's known as **Distinguished Folders**. For example, you can get the Outbox (Boîte d'envoi) with

```php
$folder = $api->getFolderByDistinguishedId(\garethp\ews\API\Type\DistinguishedFolderIdNameType::OUTBOX);
```

But I'm not sure if there's a clean way to get only the folders in your image above. You can, however, get folders that are inbox one of those. For example, if you want to get folders that a user created in the Inbox, you can do

```php
$folders = $api->getChildrenFolders(\garethp\ews\API\Type\DistinguishedFolderIdNameType::INBOX);
```

But to answer your main question: I'm not sure if there is a way to get just the folders that you see in your screenshot. There's lots of ways to get different folders, but in general accessing Exchange through this API should show you more information than the user will see. However, if you can find an article in the [Exchange Web Services Documentation](https://msdn.microsoft.com/en-us/library/office/jj900166(v=exchg.150).aspx) that's close to what you're after, I can definitely help get something working from that

**Comment by Robinouh** [comment]
Hi Gareth,

First of all I would like to thank you for your amazing work on this library !

I also thank you for your quick response, I was able to solve my problem like this:

```
$api = MailAPI::withUsernameAndPassword($server, $user, $password);

$folders = $api->getChildrenFolders(DistinguishedFolderIdNameType::MESSAGE_ROOT);

foreach($folders as $folder)
{
    if($folder->getFolderClass() == "IPF.Note")
        echo $folder->getDisplayName() . "<br>";
}
```

I filter the results in order to recover only the folders with the condition:

`if($folder->getFolderClass() == "IPF.Note")`

It works perfectly and I get this:

![capture](https://user-images.githubusercontent.com/35724895/36259410-6a54f0be-125e-11e8-871b-0aab1b02378f.PNG)

But I would like to integrate the filter directly during the search like this:

```
$options = array('folderClass' => 'IPF.Note');
$folders = $api->getChildrenFolders(DistinguishedFolderIdNameType::MESSAGE_ROOT, $options);
```

It does not work, is it possible to apply a filter directly during the search?

**Comment by Garethp** [comment]
Restrictions are actually a bit more complicated, but for now I'll supply some documentation and some code that should work for you. I'll see if I can't work on making it a little bit easier in the future. For now, restrictions are documented [on the Microsoft site here](https://msdn.microsoft.com/en-us/library/office/aa563791(v=exchg.150).aspx), with example XML found [here](https://msdn.microsoft.com/en-us/library/office/dn579422(v=exchg.150).aspx).

To get that working for you, try using this override instead 

```php
$folders = $api->getChildrenFolders(\garethp\ews\API\Type\DistinguishedFolderIdNameType::MESSAGE_ROOT, [
    'Restriction' => [
        'IsEqualTo' => [
            'FieldURI' => ['FieldURI' => \garethp\ews\API\Enumeration\UnindexedFieldURIType::FOLDER_FOLDER_CLASS],
            'FieldURIOrConstant' => ['Constant' => ['Value' => 'IPF.Note']]
        ]
    ]
]);
```

**Comment by Robinouh** [comment]
Thank you very much, it works perfectly.

**Comment by Garethp** [comment]
Good luck. Feel free to post if you have any other questions
