### ISSUE TITLE
Using php-ews without composer

### ISSUE THREAD

**Issue by basementmedia2** [Garethp/php-ews#132]
Hi,

is it possible to use the php-ews library without having composer (which is not installed at my webspace)?
If yes: Is there a basic example, how to connect to an external outlook exchange server?
In all exmaples that i've found a "vendor/autoload.php" file is required which i think is created by composer.
So i don't have this file.
Also all examples include code lines which begin with "use"-command.
Is this also some "composer"-special command?

Best regards 
Daniel

**Comment by Garethp** [comment]
Hi

It would be a pain in the ass for you to use this package without composer, but it's possible. However it's not something I support. Instead, you can install composer locally, develop your application locally and then push your code and the `vendor` folder up to your webspace as a whole. Then you won't need composer on the server.

`use` is not a composer feature, it's been a feature of PHP since 5.3. You can [read the documentation here](http://php.net/manual/en/language.namespaces.importing.php)

**Comment by basementmedia2** [comment]
Hi,

ok... you persuaded me to use composer ;-) I will update my webspace account so that i have ssh and then can install composer.

For first testing, i've installed composer on my windows system (i have xampp installed).
Then i installed your package via command "composer require garethp/php-ews" which seemed to work fine: The vendor folder and the composer.JSON file was created.

At next, i copied the file "sendMail.php" from the folder "C:\xampp\htdocs\myproject\vendor\garethp\php-ews\examples\mail" into the folder  "C:\xampp\htdocs\myproject"

But when i open the url "http://localhost/myproject/sendMail.php" i get the following error message:

Fatal error: Class 'SoapClient' not found in C:\xampp\htdocs\myproject\vendor\garethp\php-ews\src\API\NTLMSoapClient.php on line 41

Can u help me once again to get this thing running?

Best regards and thanx for your support
Daniel

**Comment by basementmedia2** [comment]
Stop: the fault was that ";extension=php_soap.dll" was commented out...
i got another fault message, but i will try to get the solution by myself and come back, if i  fail ;-)
