### ISSUE TITLE
Getting Email-ID / Open Email by ID 

### ISSUE THREAD

**Issue by basementmedia2** [Garethp/php-ews#133]
Yes! Your library is so great!
Now, i suceeded in connecting to our outlook exchange server and reading the inbox.
My (hoepfully last) problem is:

I want to display the Email subjects in a (bootstrap-)table. Next to each subject there is a "Display mail-body" button. If the user does press this button, the (javascript ajax-)function "show_mail()" should be called and the Email-ID given as parameter. Then, the show_mail() function should load and display the Mail-Body. Also i want other functions like delete_mail, forward_mail which all need the ID of the mail.

But how can i get the Mail-ID?

Here is my actual code (which generates a JSON-Object which is proceeded and displayed by a bootstrap-table:

``` <?php
require_once "vendor/autoload.php";

use garethp\ews\API\Type;
use garethp\ews\MailAPI;

$data=array();

$api = MailAPI::withUsernameAndPassword("myserver", "myusername", "mypassword");
$mail = $api->getMailItems();

foreach ($mail as $email) {
	$email = $api->getItem($email->getItemId());
	$email_id=$email->getItemId(); //Doesn't work...
	$subject = $email->getSubject();
        $sender = $email->getSender()->getMailbox()->getEmailAddress();
        $body = (string) $email->getBody();
	$buttons="<a href=\"javascript:;\" title=\"Show mail\" class=\"btn btn-default\" onclick=\"show_mail('".$email_id."');\"><span class=\"glyphicon glyphicon-zoom-in\"></span></a>
	<a href=\"javascript:;\" title=\"Delete mail\" class=\"btn btn-default\" onclick=\"delete_mail('".$email_id."');\"><span class=\"glyphicon glyphicon-save\"></span></a>";
	// Push into object
	array_push($data, array("sender" => $sender, "subject" => $subject, "body" => $body, "buttons" => $buttons)); 
}
echo json_encode($data);
?>

**Comment by Garethp** [comment]
So, the thing is that the Email ID (and all ID's in EWS) is actually made of two parts, the ID and the ChangeKey

```php
$id = $email->getItemId()->getId();
$changeKey = $email->getItemId()->getChangeKey();

$ItemId = new ItemId($id, $changeKey);
```

The actual **id** of the Email is `->getId()`. The ChangeKey is more for keeping track of which version of the item you're using. So, if you're just getting the email for read only you *should* only need the ID. But if you want to *edit* an email or a folder or a calendar item or anything you need the Change Key as well. That's so that when you send an update to the server, it can check your stored ChangeKey against the current ChangeKey of the item to make sure that the item hasn't been changed since you last fetched it.

I hope that clears things up

**Comment by basementmedia2** [comment]
Perfect, thanx!
Can i use the ID also to delete a mail?
Is deleting of mails possible/ documented?
