### ISSUE TITLE
Reading Office365 Calendar events

### ISSUE THREAD

**Issue by monkeyphysics** [Garethp/php-ews#14]
I'm not sure what's wrong here, but the following code is throwing an exception `SOAP client returned status of 403`. Any help would be greatly appreciated. Before diving in, is there some sort of debug flag for the API to get some more details about the requests/responses going on behind the scenes?

The following code correctly directs me to Office365 to authorize my application with scope `https://outlook.office.com/Calendars.ReadWrite` and redirects me back with an authorization-code. 

The autorization-code allows me to get a seemingly correct access-token with `ExchangeWebServicesAuth::getTokenFromAuthorizationCode`. So all is looking good up until that point.

However, when calling `$api->getCalendar()` the exception `SOAP client returned status of 403` is thrown.

```php
use jamesiarmes\PEWS\API;
use jamesiarmes\PEWS\API\ExchangeWebServicesAuth;

$app->get('/oauth', function() use ($app) {
	$redir = 'http://localhost:8080/oauth';

	if (!isset($_GET['code'])) {
		$oAuth = new oAuthService();
		header("Location: ".$oAuth->getLoginUrl($redir), 301);
		exit;
	}

	$token = ExchangeWebServicesAuth::getTokenFromAuthorizationCode(
		getenv('OFFICE365_CLIENT_ID'),
		getenv('OFFICE365_CLIENT_SECRET'),
		$_GET['code'],
		$redir
	);

	$api      = API::withCallbackToken('outlook.office.com', $token);
	$calendar = $api->getCalendar();
	$items    = $calendar->getCalendarItems('01-03-2016 00:00:00', '01-04-2016 00:00:00');

	var_dump($items);
});
```

As said, any help is greatly appreciated. This is probably not a true issue with the library, but some help in the right direction would be awesome.

**Comment by Garethp** [comment]
Thanks for contacting me. As it stands I don't have the ability to test out Office 365 myself, I don't have any accounts with which to develop, hence only being able to get as far as working with the Auth Token. Are there different permissions you can give the application itself? Note that this library is for EWS, the SOAP API, not the new REST API. I know that Office 365 supports EWS, but I'm not sure what permissions you need to grant the app when you register the application.

As for your other question, if you want to see the requests going in and out, try breakpoints in `NTMLSoapClient::__doRequest()`. It's done using Guzzle, so you should be able to see the requests in PSR7

**Comment by monkeyphysics** [comment]
Thanks for your reply. I will look further into this tomorrow.
Must admit that my mind is pretty clouded by Microsoft's various API's, versions, products, etc. Their documentation truly is a maze (and stuffed with 404's while on it).

I've been following this step-by-step guide to see in what direction it goes, and this seems to be working:
https://dev.outlook.com/RestGettingStarted/Tutorial/php

I will follow up.

**Comment by Garethp** [comment]
That would be their REST API. It's pretty new, and nice, but not what this library is supporting. This library is built for their Exchange Web Services, which is a SOAP API. It wraps around a WSDL file and communicates with Exchange through XML calls. The reason I built this is because my work needed to communicate with a local Exchange 2007/2010 server, and they don't support REST. The starting point for that seems to be [here](https://msdn.microsoft.com/en-us/library/office/dn789003(v=exchg.150).aspx), but that uses their Managed API as reference, which is a library they built for C#. If you google "EWS" and your use case, you'll find articles from Microsoft that explain things in C# and in XML, such as [this](https://msdn.microsoft.com/en-us/library/office/dn495614(v=exchg.150).aspx). There is zero support for PHP, and no examples for it, hence this library. 

If you only need to work with Office 365, I'd suggest not using this library and using REST from the start. REST is a nice standard to work with, and as you can see there's PHP examples for it

**Comment by monkeyphysics** [comment]
Thanks for your help and input so far. Our case was exactly the same: communicating with a local Exchange 2010 server. However, we recently migrated to Office365, and I was hoping to simply switch from `API::withUsernameAndPassword` to `API:: withCallbackToken` and be done with it.

But apparently, that won't work.

I'll dive into using the REST API, and take it from there.

**Comment by Garethp** [comment]
Sorry about that. Once I'm able to get started with Office365 at some point myself, I'll investigate the how and why it doesn't work

**Comment by Garethp** [comment]
So I've finally been able to sign up for a dev account (I wasn't able to before), and I'll be testing this now and writing up some docs. In the mean time, I used the old way of doing it and it worked without a hitch, no OAuth2 involved. Here's what I used that worked

```php

use jamesiarmes\PEWS\Mail\MailAPI as API;

$api = API::withUsernameAndPassword('https://outlook.office365.com', 'Garethp@garethp.onmicrosoft.com', 'myPasssword');

$items = $api->getMailItems();
```

What do you get when you try to use UsernameAndPassword for office365.com?

**Comment by monkeyphysics** [comment]
Oh wow. I can't believe I dit not even try that in the first place. It works!

Having seen the [workingWithOffice365.php](blob/master/examples/basic/workingWithOffice365.php) example, I jumped straight into the token-business.

Is there any reason to assume Microsoft will stop supporting the SOAP API for Office365 in the future?

**Comment by Garethp** [comment]
Probably not, no. They're very big on backwards compatibility and seem to still be supporting it and releasing new features for it. I'm still working on getting OAuth with EWS going.

**Comment by monkeyphysics** [comment]
Awesome. Let's hope this thread will help at least a few other lost souls in the future :)

**Comment by Garethp** [comment]
I've also improved the documentation for EWS over OAuth, if that's the street you want to go down. Turns out you can't have granular permissions for it, so in your Azure AD app configuration, you need to get it the "Access mailboxes as the signed-in user via Exchange Web Services" permission for "Office 365 Exchange Online"
