### ISSUE TITLE
Common question for understanding

### ISSUE THREAD

**Issue by basementmedia2** [Garethp/php-ews#140]
Hi,

actually (with my limited programming knowledge) i only act corresponding to the "trial and error" princip, means i search this forum or the examples of your library and copy / paste some code.
i am able to edit single code-lines but do not fully understand what i'm doing ;-(
So this is a basic question qhich (hopefully) helps me to understand the principle of the library.
I'm still trying to get the email signature which is saved (within my user account) in our outlook exchange server.
So i have googled for "php-ews get user signature".
Google gave me the following example code, which comes from the original library you have forked:
```
<?php
/**
 * This example shows how to list the OWA.UserOptions configuration for a user.
 */
require_once '../../vendor/autoload.php';

use \jamesiarmes\PhpEws\Client;
use \jamesiarmes\PhpEws\Request\GetUserConfigurationType;

use \jamesiarmes\PhpEws\Enumeration\DistinguishedFolderIdNameType;
use \jamesiarmes\PhpEws\Enumeration\ResponseClassType;
use \jamesiarmes\PhpEws\Enumeration\UserConfigurationPropertyType;

use \jamesiarmes\PhpEws\Type\DistinguishedFolderIdType;
use \jamesiarmes\PhpEws\Type\UserConfigurationNameType;

// Set connection information.
$host = '';
$username = '';
$password = '';
$version = Client::VERSION_2016;

$client = new Client($host, $username, $password, $version);

$request = new GetUserConfigurationType();
$request->UserConfigurationProperties = UserConfigurationPropertyType::ALL;

// Set the name of the configuration to retrieve.
$name = new UserConfigurationNameType();
$name->DistinguishedFolderId = new DistinguishedFolderIdType();
$name->DistinguishedFolderId->Id = DistinguishedFolderIdNameType::ROOT;
$name->Name = 'OWA.UserOptions';
$request->UserConfigurationName = $name;

$response = $client->GetUserConfiguration($request);

// Iterate over the results, printing any error messages or options and their
// values.
$response_messages = $response->ResponseMessages
    ->GetUserConfigurationResponseMessage;
foreach ($response_messages as $response_message) {
    // Make sure the request succeeded.
    if ($response_message->ResponseClass != ResponseClassType::SUCCESS) {
        $message = $response_message->ResponseCode;
        fwrite(
            STDERR,
            "Failed to get User Configuration with \"$message\"\n"
        );
        continue;
    }

    $config = $response_message->UserConfiguration;
    $name = $config->UserConfigurationName->Name;
    foreach ($config->Dictionary->DictionaryEntry as $entry) {
        $key = $entry->DictionaryKey->Value[0];
        $value = implode(', "', $entry->DictionaryValue->Value);
        fwrite(STDOUT, "$name.$key = \"$value\"\n");
    }
}
```

But now the problem is, that i don't know, how to edit this example to make it work with your library.

I think, first i have to change the use's as follows

```
use garethp\ews\API\Type;
use garethp\ews\MailAPI;
use garethp\ews\API\Enumeration\DistinguishedFolderIdNameType;
use garethp\ews\API\Message\GetUserConfigurationType;
use garethp\ews\API\Enumeration\UserConfigurationPropertyType;
use garethp\ews\API\Enumeration\ResponseClassType;
use garethp\ews\API\Type\DistinguishedFolderIdType;
use garethp\ews\API\Type\UserConfigurationNameType;

```
And this line:
```
$client = new Client($host, $username, $password, $version);
```

has to become this 

```
$api = MailAPI::withUsernameAndPassword("myserver", "myuser", "mypassword");
```

And from this point on, i don't know how to edit the rest ;-(

So transfering this example to your library would be a hello world experience that would hopefully help me to post less issues ;-)

Again i hope for your great help.

Best regards and thanx for your endless patience
Daniel

**Comment by Garethp** [comment]
Hi there.

So the first thing to understand and see is that what that library does and what mine do are basically the same thing. We build an object that gets converted to XML (by PHP's SOAP client) that communicates with Exchange Web Services. Exchange Web Services responds with XML and then that gets transformed in to PHP Objects being being returned to you. The main difference comes down to *how we go about creating the request object*. Let me start with a simpler example. I'll use creating a folder to start with.

Looking at [the example on creating a folder in the original `php-ews`](https://github.com/jamesiarmes/php-ews/blob/master/examples/folder/create.php), we can see what's he's doing. I'll get the most important part for you

```php
$client = new Client($host, $username, $password, $version);

// Build the request object.
$request = new CreateFolderType();
$request->Folders = new ArrayOfFoldersType();

// Set the parent folder for the newly created folder.
$parent = new TargetFolderIdType();
$parent->DistinguishedFolderId = new DistinguishedFolderIdType();
$parent->DistinguishedFolderId->Id = DistinguishedFolderIdNameType::CALENDAR;
$request->ParentFolderId = $parent;

// Configure the new folder to be created. You could create multiple folders in
// a single request.
$folder = new CalendarFolderType();
$folder->DisplayName = 'New Calendar Folder';
$request->Folders->CalendarFolder[] = $folder;

$response = $client->CreateFolder($request);
```

The import things that's happening there are: 

 * Create the SOAP Client
 * Build the CreateFolder Request
 * Tell the SOAP Client to send a `CreateFolder` **operation** to EWS

We know that `$client->CreateFolder($request)` is the operation, so we can look that up. So we google "ews create folder" and the first link is documentation from `https://msdn.microsoft.com`, which is perfect for us. It's talking about using Manage API 2.0, which is a C# library that Microsoft maintains, but their documentation always comes with XML request and responses. After all, even their library is just trying to make the SOAP easier. So we [open the documentation page](https://msdn.microsoft.com/en-us/library/office/dd633637(v=exchg.80).aspx) and scroll down to the XML example and see: 

```xml
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
               xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages" 
               xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types" 
               xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/">
  <soap:Header>
    <t:RequestServerVersion Version="Exchange2010" />
  </soap:Header>
  <soap:Body>
    <m:CreateFolder>
      <m:ParentFolderId>
        <t:DistinguishedFolderId Id="drafts" />
      </m:ParentFolderId>
      <m:Folders>
        <t:Folder>
          <t:FolderClass>IPF.MyCustomFolderClass</t:FolderClass>
          <t:DisplayName>Custom Folder</t:DisplayName>
          <t:PermissionSet>
            <t:Permissions />
          </t:PermissionSet>
        </t:Folder>
      </m:Folders>
    </m:CreateFolder>
  </soap:Body>
</soap:Envelope>
```

Is the XML structure that we're trying to make. He's adding some extra things that aren't in the XML, but that's fine. We know what the XML should look like. Now let's see how we do the same thing in my library. What does `API::createFolders` look like?

```php
    public function createFolders($names, BaseFolderIdType $parentFolder, $options = array(), $folderClass = null)
    {
        $names = Utilities\ensureIsArray($names);
        $names = array_map(function ($name) use ($folderClass) {
            return ['DisplayName' => $name, 'FolderClass' => $folderClass];
        }, $names);

        $request = [
            'Folders' => ['Folder' => $names]
        ];

        if ($parentFolder !== null) {
            $request['ParentFolderId'] = $parentFolder->toArray(true);
        }

        $request = array_merge_recursive($request, $options);

        $this->client->CreateFolder($request);
        return true;
    }
```

So what are we actually doing here? We're taking an array of names, and turning then in an array where the name is called `DisplayName`, and we allow an optional `FolderClass`. We then put it in an array key called `Folders`, and we allow an optional `ParentFolderId`. We allow the person who calls it to pass in an `$options` array that we will merge in with what we've got to customize the array. Then we take that request and pass it in to `$this->client->CreateFolder`. 

Okay, but what would `$request` look like if we called the function, say, `createFolder([ 'folder1', 'folder2' ], new t:DistinguishedFolderId ('drafts'));`? It would look something like this

```php
$request = [
    'Folders' => [
        'Folder' => [
            ['DisplayName' => 'folder1'],
            ['DisplayName' => 'folder2'],
        ],
    ],
    'ParentFolderId' => [
        'DistinguishedFolderId' => [ 'Id' => 'drafts']
    ]
];
```

Compare that to the XML from above. We skip permission set and folder class, since those are optional. How do I know that? Okay, I cheated a bit. I googled "ews createfolder operation" to get [the documentation for the Operation itself](https://msdn.microsoft.com/en-us/library/office/aa563574(v=exchg.150).aspx) and saw another example. It also gives you links to tell you what, say the [`Folder`](https://msdn.microsoft.com/en-us/library/office/aa581334(v=exchg.150).aspx) element of the XML can look like. 

But that's not important, what's important is that you can see how my Array looks like the XML. And how what the original library does is trying to do the same thing, just with PHP Objects instead of an Array. There's a whole bunch of crap under the hood to my library about why you're allowed to just pass in an array, but you can. That's actually the first change I made, allow all of those complicated objects to be built from an array.

On to your request. What is the code you pulled trying to do? Well, `$response = $client->GetUserConfiguration($request);` says that we want to call the `GetUserConfiguration` operation on EWS. Docs for the [`GetUserConfiguration`](https://msdn.microsoft.com/en-us/library/office/dd899439(v=exchg.150).aspx) show that the XML should look something like 

```xml
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
               xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"
               xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
               xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <soap:Header>
    <t:RequestServerVersion Version="Exchange2010" />
  </soap:Header>
  <soap:Body>
    <m:GetUserConfiguration>
      <m:UserConfigurationName Name="TestConfig">
        <t:DistinguishedFolderId Id="drafts"/>
      </m:UserConfigurationName>
      <m:UserConfigurationProperties>Dictionary</m:UserConfigurationProperties>
    </m:GetUserConfiguration>
  </soap:Body>
</soap:Envelope>
```

But what XML would

```php
$request = new GetUserConfigurationType();
$request->UserConfigurationProperties = UserConfigurationPropertyType::ALL;

// Set the name of the configuration to retrieve.
$name = new UserConfigurationNameType();
$name->DistinguishedFolderId = new DistinguishedFolderIdType();
$name->DistinguishedFolderId->Id = DistinguishedFolderIdNameType::ROOT;
$name->Name = 'OWA.UserOptions';
$request->UserConfigurationName = $name;
```

Make? I think it would look similar to this

```xml
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns:m="http://schemas.microsoft.com/exchange/services/2006/messages"
               xmlns:t="http://schemas.microsoft.com/exchange/services/2006/types"
               xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
               xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <soap:Header>
    <t:RequestServerVersion Version="Exchange2010" />
  </soap:Header>
  <soap:Body>
    <m:GetUserConfiguration>
      <m:UserConfigurationName Name="OWA.UserOptions">
        <t:DistinguishedFolderId Id="root"/>
      </m:UserConfigurationName>
      <m:UserConfigurationProperties>all</m:UserConfigurationProperties>
    </m:GetUserConfiguration>
  </soap:Body>
</soap:Envelope>
```

So how would we make that XML from an array? Let's try...

```php
use garethp\ews\API;
use garethp\ews\API\Enumeration\DistinguishedFolderIdNameType;
use garethp\ews\API\Enumeration\UserConfigurationPropertyType;

require_once __DIR__ . '/vendor/autoload.php';

$client = API::withUsernameAndPassword('server', 'user', 'password');

$response = $client->getClient()->GetUserConfiguration([
    'UserConfigurationName' => ['Name' => 'OWA.UserOptions'],
    'DistinguishedFolderId' => ['Id' => DistinguishedFolderIdNameType::ROOT],
    'UserConfigurationProperties ' => UserConfigurationPropertyType::ALL
]);
```

Well, I don't have an account I can test this on right now, so you'll have to try it and let me know how it goes. But what about the response? He handles the response code in a complicated way. My library does most of that `ResponseMessages` and `ResponseClassType` stuff for you. So you *should* just get an instance of `garethp\ews\API\Type\UserConfigurationType` back, hopefully. You may want to check it yourself.

I hope that explains roughly how this library works. And how his works. It's all about creating the XML request to send to Exchange. His works through creating the objects by hand and passing it in, I let you define an array instead. You *can* still create objects with my library, and it can be helpful in some places, but you don't have to.

Any questions?

**Comment by basementmedia2** [comment]
Hey Gareth,

Thanx a lot for this great explanation!!
I will read and try to understand all you wrote the next few days and try the user-configuration example.
I will come back next week and post my experiences;-)

Have a nice evening.

Best regards 
Daniel

**Comment by basementmedia2** [comment]
Hi Gareth,

i think that i have understood the whole thing "roughly".
But when i try your GetUserConfiguration Example:

```
<?php
require_once "vendor/autoload.php";
use garethp\ews\API;
use garethp\ews\API\Enumeration\DistinguishedFolderIdNameType;
use garethp\ews\API\Enumeration\UserConfigurationPropertyType;

$client = API::withUsernameAndPassword("myserver", "my_user", "my_password");

$response = $client->getClient()->GetUserConfiguration([
    'UserConfigurationName' => ['Name' => 'OWA.UserOptions'],
    'DistinguishedFolderId' => ['Id' => DistinguishedFolderIdNameType::ROOT],
    'UserConfigurationProperties ' => UserConfigurationPropertyType::ALL
]);

print_r($response);

?>
```
i get the following error:

```
Fatal error: Uncaught SoapFault exception: [Client] SOAP-ERROR: Encoding: object has no 'UserConfigurationProperties' property in [...]/vendor/garethp/php-ews/src/API/NTLMSoapClient.php:118 Stack trace: #0 [...]/vendor/garethp/php-ews/src/API/NTLMSoapClient.php(118): SoapClient->__call('GetUserConfigur...', Array) #1 [...]/vendor/garethp/php-ews/src/API/ExchangeWebServices/MiddlewareFactory.php(18): garethp\ews\API\NTLMSoapClient->__call('GetUserConfigur...', Array) #2 [...]/vendor/garethp/php-ews/src/API/ExchangeWebServices.php(497): garethp\ews\API\ExchangeWebServices->garethp\ews\API\ExchangeWebServices\{closure}(Object(garethp\ews\API\MiddlewareRequest), Object(Closure)) #3 [...]/vendor/garethp/php-ews/src/API/ExchangeWebServices/MiddlewareFactory.php(32): garethp\ews\API\ExchangeWebServices->garethp\ews\API\{closure}(Object(garethp\ews\API\MiddlewareRequest)) #4 /www/htdocs/w00c2ecf/s in[...]/vendor/garethp/php-ews/src/API/NTLMSoapClient.php on line 118
```
Also i wonder where to find the getUserConfiguration function (to see how the function works and what parameters are to be set).

The createFolders function i have found in the file API.php in the root dir (although the second parameter is different to the function code you posted):
```
public function createFolders($names, Type\FolderIdType $parentFolder, $options = array(), $folderClass = null)
```
in your example "Type\FolderIdType $parentFolder" is "BaseFolderIdType $parentFolder"

But where can i find the function GetUserConfiguration?

Best regards
Daniel

**Comment by basementmedia2** [comment]
Hey Gareth,

i've tried a little bit with your code and this way it works

```
require_once "vendor/autoload.php";

use garethp\ews\API;
use garethp\ews\API\Enumeration\DistinguishedFolderIdNameType;
use garethp\ews\API\Enumeration\UserConfigurationPropertyType;

$client = API::withUsernameAndPassword("myserver", "myuser", "mypassword");

$request = [
	'UserConfigurationName' => [
		'Name' => 'OWA.UserOptions',
		'DistinguishedFolderId' => ['Id' => DistinguishedFolderIdNameType::ROOT]
	],
	'UserConfigurationProperties' => UserConfigurationPropertyType::ALL
];

$response = $client->getClient()->GetUserConfiguration($request);

print_r($response);
```

But unfortunately, the result does not contain the information i expected: The user signature. ;-(

Best regards

Daniel

**Comment by Garethp** [comment]
Hi

Sorry for not replying earlier. Are you sure you didn't get the information you want? It looks like it *mighht* be in the `$response->getDictionary()` object somewhere.

So, doing `'UserConfigurationProperties' => 'all'` would have worked. No problem there. But they do also exist in enumeration objects so that you can use autocompletion if you want. 

> Where can i look-up things like "UserConfigurationPropertyType::ALL" (or DistinguishedFolderIdNameType::ROOT)?

Well, you *can* look in the `API\Enumeration` folder to see the complete list of files that have enumeration, but there's a lot of them. If you're using an IDE like PhpStorm (Which I would highly recommend), it should help you by autocompleting when you start typing, or tell you all of the options in `UserConfigurationPropertyType` for example. Is that what you meant?

**Comment by basementmedia2** [comment]
Hi Gareth,

no it works.
It was an internal problem of outr outlook server.
The email signature was saved at another place. Now this setting has changed and it works for me.
I've posted the solution in my other issue thread "getting the email signature".

Thanx for your great support again!

Daniel

**Comment by Garethp** [comment]
Thanks for the update!
