### ISSUE TITLE
Access Calendar from other User

### ISSUE THREAD

**Issue by fglueck** [Garethp/php-ews#156]
I try to fetch the calendar of an other user without impersonation.
The User gives me the right to read/write/create appoints inside a specified calendar.

`$api->getChildrenFolders(Enumeration\DistinguishedFolderIdNameType::CALENDAR);`

Returns only my calendars.

```php
$api->getChildrenFolders(Enumeration\DistinguishedFolderIdNameType::CALENDAR,
    array('ParentFolderIds' => array('DistinguishedFolderId'=> array('id'=>'Test-Kalender', 'Mailbox'=>array('EmailAddress'=>'xxxx@xxx.xx'))))
));
```

Returns: The request failed schema validation: The 'Id' attribute is invalid
But this is the valid displayname from the calendar.

```php
$api->getChildrenFolders(Enumeration\DistinguishedFolderIdNameType::CALENDAR,
    array('ParentFolderIds' => array('DistinguishedFolderId'=> array('id'=>'calendar', 'Mailbox'=>array('EmailAddress'=>'xxxx@xxxx.xx'))))
));
```

Uncaught garethp\ews\API\Exception\ExchangeException: The specified folder could not be found in the store

What I do wrong? Or is this completly wrong?
I get the idea to do this from here:
https://docs.microsoft.com/de-de/exchange/client-developer/exchange-web-services/how-to-access-a-calendar-as-a-delegate-by-using-ews-in-exchange
```xml
      <m:ParentFolderIds>
        <t:DistinguishedFolderId Id="calendar">
          <t:Mailbox>
            <t:EmailAddress>primary@contoso.com</t:EmailAddress>
          </t:Mailbox>
        </t:DistinguishedFolderId>
      </m:ParentFolderIds>
```

**Comment by Garethp** [comment]
So there's a couple of things to note here. You're on the right track with

```php
$api->getChildrenFolders(Enumeration\DistinguishedFolderIdNameType::CALENDAR,
    array('ParentFolderIds' => array('DistinguishedFolderId'=> array('id'=>'Test-Kalender', 'Mailbox'=>array('EmailAddress'=>'xxxx@xxx.xx'))))
));
```

But the problem is that `Test-Kalender` is not a `DistinguishedId`. A `DistinguisedId` is basically a reserved ID for a built-in folder that comes with Exchange, not one that's created by the user. So `calendar` is a DistinguisedId, so is `inbox`, `contacts`, `root` and a few others. You can see the full list in `garethp\ews\API\Enumeration\DistinguisedFolderIdNameType`. Furthermore, these are the same across all languages. So even if the exchange shows you something other than `Inbox` on the web, the **Id** is still `inbox`. 

Now, you're closer with

```php
$api->getChildrenFolders(Enumeration\DistinguishedFolderIdNameType::CALENDAR,
    array('ParentFolderIds' => array('DistinguishedFolderId'=> array('id'=>'calendar', 'Mailbox'=>array('EmailAddress'=>'xxxx@xxxx.xx'))))
));
```

But the issue is that you're asking for `Calendar`, but using `getChildrenFolders`, so you're looking for the Calendar folder inside the Calendar folder. What you could do is:

```php
$mailbox = new EmailAddressType();
$mailbox->setEmailAddress('xxx@xxx.xxx');
$distinguisedId = new DistinguisedIdFolderType('calendar', null, $mailbox);
$folder = $api->getFolderByFolderId($distinguishedId);
```

But I've actually already provided a much simpler way of doing that. You can [set the Primary SMTP Mailbox you want to access](https://github.com/Garethp/php-ews/blob/master/examples/basic/primarySmtpAddress.php) and just use that. So you'd do

```php
$api = API::withUsernameAndPassword(
    'server',
    'username',
    'password',
    [
        'primarySmtpEmailAddress' => 'secondaryEmail@test.com'
    ]
);

$folder = $api->getFolderByDistinguishedId('calendar');
```

Or once it's set, if you just want the ID and not the whole folder you can do

```php
$folderId = $api->getDistinguishedFolderId('calendar');
```

So that would be more useful if you wanted to list the different calendars in their account

**Comment by Garethp** [comment]
Did this end up working for you?

**Comment by Traxxas10** [comment]
Hello,
I have the same problem, and use your code. Problem: the folderID is empty?

```
$api = API::withUsernameAndPassword(
    $server,$username ,$password,
    [
        'primarySmtpEmailAddress' => $email
    ]
);

$folderId = $api->getDistinguishedFolderId('calendar');

echo 'folderId: '.$folderId;
```


and now, If i say:
`$calendar = $api->getCalendar();`

I still got my own calender. How can i join the calendar of $email?

best regards
