### ISSUE TITLE
How to fetch Recurring Series Event of Master Event?

### ISSUE THREAD

**Issue by yogita29Sharma** [Garethp/php-ews#166]
Is there any sample code to Fetch Recurring Child Events of a Master Event?

**Comment by ianobre** [comment]
I need to knew the same think

**Comment by ianobre** [comment]
@Garethp , save us :-(

**Comment by yogita29Sharma** [comment]
The following chunk of code will help you to find the series. Firstly you have to make the array of Indexes. here indexes are the number of child events in Master Event.


```
$request = array(
                'ItemShape' => array('BaseShape' => 'AllProperties','BodyType' => 'Text'),
                'ItemIds' => array('OccurrenceItemId' => array("RecurringMasterId" => $masterId, "InstanceIndex" => $index))
            );
            
            try{
                
                $response = $api->getClient()->GetItem($request);
           } catch (Exception $e){
                $error = $e->getMessage();
            }
```

**Comment by Garethp** [comment]
Sorry I didn't reply, but @yogita29Sharma has it right. As far as I'm aware you can only get one item at a time, so you need to loop through them manually one at a time. There might be another way, but this is my understanding. I believe that this is because Recurring items aren't actually created and stored in the database individually, but actually calculated on the fly (or similar) on each request due to how flexible and infinite recurring events can be
