### ISSUE TITLE
Message ID to identify a Message....

### ISSUE THREAD

**Issue by tomlp** [Garethp/php-ews#182]
Dear Garethp,
i worked a while with your library and i´am impressed for the speed in contrast of IMAP :) 
I build up a template-class to handle IMAP & EWS accounts in a same way.
From IMAP i get a single identifier for a message and put it into a database table to store it for faster access and find it again for updates from the IMAP-Server.
But in EWS i got only a pair of - at minimum two - long fields (within itemId the Id & changeKey) for a message. Is there a way to calculate a single messageID for a message that i can use for searching in the puffer-database and (hopefully) to get the message with this single key from the Server too?
As i saw for now, the message could only identified with the combination of changeKey & Id...
Did i miss something ?
My current idea is to append the Id to changeKey (it seams to changed more often) and create the index long enough to identify the single message. But may be there is a better (and saver) solution to identify the single message :)
kr Tom

**Comment by Garethp** [comment]
The `Id` identifies the message, while the `ChangeKey` is there to identify the version of the message in Exchange. So the `Id` will always refer to that message, with or without the ChangeKey. The ChangeKey is used so that you don't try to perform an update on an outdated version of the message. If you're just using the Id to look for the message and not to update it, you don't need the ChangeKey

**Comment by tomlp** [comment]
Der Garethp,
thx for clarification - so i had to expand the index itself to hold the looooong Key :)
thx - also for your time & (hard) work :)
kr Tom

**Comment by tomlp** [comment]
Sorry - one Question is open - could the Id only used to get the message ?

**Comment by Garethp** [comment]
Yes, you can. You can get an item with just the Id
