### ISSUE TITLE
FileAttachments

### ISSUE THREAD

**Issue by BlazingSun** [Garethp/php-ews#37]
Hi

uploadContactPhoto example is not working, because client does not have a method CreateAttachment(). I wanted to attach some files to an outgoing email. I guess it works the same as for contact photos?

**Comment by Garethp** [comment]
Do you have a PHP error you can paste? That example was pasted directly from a test file that worked for me.

**Comment by BlazingSun** [comment]
Hey, sorry for the issue. It is working without problems. I got confused because my IDE did not show autocompletion.

**Comment by BlazingSun** [comment]
Works for mail items too

```php
$this->api->getClient()->CreateAttachment(array(
                    'ParentItemId' => $itemId->toArray(),
                    'Attachments' => array('FileAttachment' => array(
                        'Name' => $attachment->getName(),
                        'Content' => $content,
                        'ContentType' => 'text',
                        'IsContactPhoto' => false
                    ))
                ));
´´´

**Comment by Garethp** [comment]
No problem, I thought that might be the case. It's something I want to get around to eventually. The reason is that the `->getClient()` return is a SOAP client. It's methods don't really exist, but rather implement a magic `__call` on the language level to pass them as SOAP functions to the server. They're undocumented because there's a hell of a lot of them and I don't know them all. At some point I want my code generator to generate all of the methods you can use, but until then IDE's won't know what you're calling
