### ISSUE TITLE
Paging

### ISSUE THREAD

**Issue by hehol** [Garethp/php-ews#45]
I'm trying to read contacts from a public folder on Exchange 2013. I managed to read from public folders on my server successfully using the ContactsAPI. But the getContacts() methods throws an exception if the folder contains more than 1000 elements.

I'm new to EWS, so I searched a bit and found out that I have to use paging to avoid hitting the 1000 elements per request limit on the server. How do I do that with the ContactsAPI or php-ews in general? All of the examples that I found don't seem to work with this version of php-ews.

**Comment by Garethp** [comment]
If the examples are done in XML, you should be able to replicate them in `php-ews`, since all `php-ews` does is build an array and then convert that to an object, but I'll take a look and see what I can find out

**Comment by hehol** [comment]
I used https://github.com/Garethp/php-ews/issues/43 and http://stackoverflow.com/questions/12300863/php-and-exchange-web-services-fetching-the-message-body-using-php-ews as starting points for my code.

Unfortunately, I cannot even instantiate the the web service object using ExchangeWebServices::fromUsernameAndPassword() without getting PHP warnings, so I assume that that part of the API is deprecated.

**Comment by Garethp** [comment]
It is, and will be removed in the next release. Instead, take a look through my [`examples/`](https://github.com/Garethp/php-ews/tree/master/examples) folder, which (I believe) should be pretty easy to read.

Issue #43 isn't a good place to start if you want examples, since I was trying to help him use my library along side an older library that I have no control of. The only reason I directed him here is that the old library has no support and so there wouldn't be much else place for him to get help. His solution was more along the lines of just using that library the proper way, instead of having anything to do with my library.

Instead of talking to `ExchangeWebServices` directly, I'd suggesting starting with the `API` class, or one that extends from it. For example, take a look at how to get a list of [`how to fetch a list of contacts`](https://github.com/Garethp/php-ews/blob/master/examples/contacts/listContacts.php). If you take a look at the source code of [`ContactsAPI::getContacts()`](https://github.com/Garethp/php-ews/blob/master/src/Contacts/ContactsAPI.php#L40), you'll see that all I do is take some variables and make a decent array from it, then create an object from that array. No paging involved, which is what you want. However, I have implemented paging in [`CalendarAPI::getCalendarItems()`](https://github.com/Garethp/php-ews/blob/master/src/Calendar/CalendarAPI.php#L108) (Well, kind of. I've limited how it's retrieved, not how to get the next page), so we could do something similar here. I'll implement the same auto-limitation in ContactsAPI in my next release, as well as an easier way to get the next page. So I'll just talk about how to do it before I make my `0.9.0` release.

So, the first step will be to override the array being created in [`ContactsAPI::getContacts()`](https://github.com/Garethp/php-ews/blob/master/src/Contacts/ContactsAPI.php#L40). Luckily, the signature of the method gives us a clue in the `$options = array()` parameter and the line `$request = array_replace_recursive($request, $options);`. So basically we can just use that. So try something like

```php
$api = ContactsAPI::withUsernameAndPassword($host, $username, $password);
$firstThousandContacts = $api->getContacts(null, [
    'IndexedPageItemView' => [
        'MaxEntriesReturned' => 100,
        'Offset' => 0,
        'BasePoint' => 'Beginning'
    ]
]);
```

Now, this begs the natural question "Where did we get this array? It's different from what's in CalendarAPI". Simple, [MSDN Docs](https://msdn.microsoft.com/en-us/library/office/dd633698(v=exchg.80).aspx) show how it's done. The docs for this example is written for their C# library, which is a bit annoying, but it shows the XML document sent and received, which is the important part. So just scroll down to the XML part and take a look. That's what our array will come out looking like. You can see where you would set your offset as well. You'll want to dump the object you've received back from this to see what you're dealing with. I'm sorry, I just don't have enough test data to have really delved in to paging so far.

I hope this post has been helpful

**Comment by Garethp** [comment]
Did this work for you?

**Comment by BlazingSun** [comment]
Hey, i am using this in my project and it works fine.
```
'IndexedPageItemView' => array(
     'MaxEntriesReturned' => 100,
     'Offset' => $offset,
     'BasePoint' => "Beginning",
```

**Comment by Garethp** [comment]
Thanks. In this case I'll close this issue
