### ISSUE TITLE
reading calendar

### ISSUE THREAD

**Issue by erickengelke** [Garethp/php-ews#64]
I have two issues:

I need to read calendar items of other people, eg userid: joe.  They have granted me full access.  I'm stuck on how to do that with garethp.  I had it working with jamesiarmes, but am trying to move forward.

Also, all the examples return a structure filled with private data I'm not allowed to read.  How do I enumerate through the list of events, and extract the date/time/topic of meetings?

So I'm hopefully asking for a simple example.

Thanks
Erick

**Comment by Garethp** [comment]
Hi Erick

You can access any private property through the use of getters and setters. For example, if there's a private property called `firstName`, try calling `getFirstName()`.

If you are able to have the code working in jamesairmes, can you post it here? I'll have a better idea of how to help you transfer your code if I can see what you're doing

**Comment by erickengelke** [comment]
That helps a lot!  But what I'm still unsure about is how to iterate through the messages.  

My code converts it to ICAL format
    $icsdetails = "BEGIN:VCALENDAR".chr(10);
    $icsdetails = $icsdetails."VERSION:1.1".chr(10);
    $icsdetails = $icsdetails."PRODID:-//erickengelke.com ".  (date_offset_get( new DateTime)/60)."/NONSGML v1.0//EN".chr(10);

    // Loop through each item if event(s) were found in the timeframe specified
    if ($response->ResponseMessages->FindItemResponseMessage->RootFolder->TotalItemsInView > 0){
        $events = $response->ResponseMessages->FindItemResponseMessage->RootFolder->Items->CalendarItem;
        foreach ($events as $event){
            $start = $event->Start;
            $end = $event->End;
            $subject = $event->Subject;
            $location = $event->Location;
            // ics detail
            $icsdetails = $icsdetails."BEGIN:VEVENT".chr(10);
            // clean date
            $cleandate = array("-", ":");
            $icsdetails = $icsdetails."DTSTART:".str_replace($cleandate, "", $start).chr(10);
            $icsdetails = $icsdetails."DTEND:".str_replace($cleandate, "", $end).chr(10);
            $icsdetails = $icsdetails."SUMMARY:".$subject.chr(10);
            $icsdetails = $icsdetails."LOCATION:".$location.chr(10);
            $icsdetails = $icsdetails."END:VEVENT".chr(10);
        }
    }
    else {
        // No items returned
    }

    // ics footer
    $icsdetails = $icsdetails."END:VCALENDAR".chr(10);

    // write ics file
    $fileout="ics/$username.ics";
    print( $icsdetails);

**Comment by erickengelke** [comment]
Okay, I got all that working.  Now my last problem is that I need to get a folder owned by someone else.

In JamesIArmes I used

  $request->ParentFolderIds = new EWSType_NonEmptyArrayOfBaseFolderIdsType();
    $request->ParentFolderIds->DistinguishedFolderId = new EWSType_DistinguishedFolderIdType();
    $request->ParentFolderIds->DistinguishedFolderId->Id = EWSType_DistinguishedFolderIdNameType::CALENDAR;
    $request->ParentFolderIds->DistinguishedFolderId->MailBox = new EWSType_MailboxData();
    $request->ParentFolderIds->DistinguishedFolderId->Mailbox->EmailAddress = "$foruser@connect.uwaterloo.ca"; // the person whose folder I am using
    // Send request
    $response = $ews->FindItem($request);

before all my get calendar code.  Now I don't know what function to call, as doing getCalendar( $foruser); is not the right thing to do.

So close I can taste it.

Erick

**Comment by Garethp** [comment]
Sorry for the late response. I'm not sure if you're iterating through calendar items right, so I'll post how to do it here

```php
use garethp\ews\API;

$api = API::withUsernameAndPassword('server', 'username', 'password');
$calendar = $api->getCalendar();

//Get all items from midday today
$items = $calendar->getCalendarItems('12:00 PM');

//Get all items from 8 AM to 9 AM today
$start = new DateTime('8:00 AM');
$end = new DateTime('9:00 AM');
$items = $calendar->getCalendarItems($start, $end);

//Get a list of items in a Date Range
$items = $calendar->getCalendarItems('31/05/2015', '31/06/2015');

foreach ($items as $item) {
    $subject = $item->getSubject();
}
```

As for what you were using, if you look at the source code for the functions you call, you can modify the requests to look however you want. So, the original request is build as an array, like so

```php
        $request = array(
            'Traversal' => 'Shallow',
            'ItemShape' => array(
                'BaseShape' => 'AllProperties'
            ),
            'CalendarView' => array(
                'MaxEntriesReturned' => 100,
                'StartDate' => $start->format('c'),
                'EndDate' => $end->format('c')
            ),
            'ParentFolderIds' => array(
                'FolderId' => $this->getFolderId()->toXmlObject()
            )
        );
```

And the signature of the method you should be using is

```php
public function getCalendarItems($start = '12:00 AM', $end = '11:59 PM', $options = array())
```

So you can pass in extra items in to the third parameter to add to modify to the original request. So, to add the code the way you did with the old library, it *should* look like this (Play around to test and make it look right yourself)

```php
$items = $calendar->getCalendarItems(default, default, array (
    'ParentFolderIds' => array (
        'DistinguishedFolderId' => array (
            'Id' => 'calendar',
            'Mailbox' => array (
                'EmailAddress' => 'emailToCheck'
            )
        )
    )
));
```

It's a bit verbose, and there might be better ways of finding out how to do it (Maybe add some options to the `getFolder*()` methods to get the `folderId`, and passing that in to `pickCalendar`, so it stays for every request), but that's a good start to get it working I would say

**Comment by erickengelke** [comment]
Yes, that solved it!!!! Thanks!!!!

**Comment by Garethp** [comment]
Great to hear it!

**Comment by beekerstudios** [comment]
Forgive me if this is hijacking this issue, but it's not clear how the example code given would result in retrieving a calendar for which the logged in user had delegate permissions to. I too was trying to repurpose some working JamesIArmes php-ews code/usage to no avail.

Which function do I call with this request?
`$token = "forcing token for testing";

$api = API::withCallbackToken('outlook.office365.com', $token);

$calendar = $api->getCalendar();

$items = $calendar->getCalendarItems(new DateTime('1:00 AM'), new DateTime('11:59 PM'), array (
    'ParentFolderIds' => array (
        'DistinguishedFolderId' => array (
            'Id' => 'calendar',
            'Mailbox' => array (
                'EmailAddress' => 'otheruser@somecompany.com'
            )
        )
    )
));
`

The below starts to fall apart when leveraging this code in this capacity but the simple item->getSubhect() call does work on the logged in users calendar, so it's not all wrong, just not for this particular use case

`foreach ($items as $item) {
    echo $item->getSubject(); // this returns an error: Uncaught exception 'Exception' with message 'Property Subject does not exist' in ../vendor/garethp/php-ews/src/API/MagicMethodsTrait.php:118
    
    print_r($item->getItems()->getCalendarItem()); //this returns the object

    echo $item->getItems()->getCalendarItem()->getSubject(); //Returns: Call to a member function getSubject() on a non-object
}`

**Comment by erickengelke** [comment]
$items = $calendar->getCalendarItems($start, $end, $par);


  if ( !isset( $items ) ) exit;

    // Loop through each item if event(s) were found in the timeframe
specified
    $c = count($items);
    for ($k = 0 ; $k < $c ; ++$k ) {
       $group = $items[$k];
       $its = $group->getItems();


       for ( $j = 0 ; $j < count( $its ) ; ++$j ) {
          $event = $its[$j];

         if ( $event == NULL ) continue;

            $start = $event->getStart();
            $end = $event->getEnd();
            $subject = $event->getSubject();
       ....

Erick

**Comment by beekerstudios** [comment]
I realized the error in my ways after I started doing some desperate things:


Warning: Don't do this for various reasons, as it's allowing access to protected data, but for troubleshooting what was going in, it immediately showed me that the data I was seeing was from the user calendar I was logged in as, as well as the other users calendar, so the main object items are in fact 2 different calendars, with their own items, and your comment made that pretty clear
```
foreach ($items as $item) {
	$calItem = $item->getItems();
	$arrayItems = (array) $calItem;
	var_dump($arrayItems["\0*\0subject"]);	
}
```


With that said in a more clear and clean manner here is the full working example:

```
$token = "forcing token for testing";

$api = API::withCallbackToken('outlook.office365.com', $token);

$calendar = $api->getCalendar();

$options = array (
    'ParentFolderIds' => array (
        'DistinguishedFolderId' => array (
            'Id' => 'calendar',
            'Mailbox' => array (
                'EmailAddress' => 'otheruser@somecompany.com'
            )
        )
    )
);

$calendars = $calendar->getCalendarItems(new DateTime('1:00 AM'), new DateTime('11:59 PM'), $options);

foreach ($calendars as $cal) {	
	foreach ($cal->getItems() as $event) {
		var_dump($event->getSubject());
	}
}
```

This is such a common thing to do, and the reality as well is the Office 365 Graph API doesn't even allow you to do this using OAuth (you can however using Basic Auth, but for SSO gateways that does not work, and also presents a CORS issue as well), without opening up Pandora's box and giving an "app token" full unabridged access to a tenant instance. For a large org, that is a scary level of access to have a token for. I prefer to still use the SOAP API because I can lock down a "service" account with delegate permissions to only the calendars it needs access to, and in my case that is room resources.

I feel like this is a bit of a break through on my end and this library, and leveraging OAuth and Exchange Online, it would be highly beneficial to have an example of just this behavior in the calendar examples. Just my 2 cents.

**Comment by Garethp** [comment]
Huh, that's really interesting behavior that I didn't know was happening. I don't know all of the behaviors of Exchange, which is why my library merely wraps around it and doesn't try to hide it if you really want to do things your own way, such as this. For example, none of the protected data you see is trying to be hidden. All of it can be accessed through getters and setters. They're protected to enforce PSR-2 standards and so that I can intercept certain functions to improve them (such as using setBody() to detect if you're sending a string, and creating a body class out of that (I don't know if I'm doing that. If I'm not, I should)). 

I'll document it, and I'll try to see if I can't find a way to combine the two results so that you don't need to do a foreach inside a foreach. It just means attempting to replicate this in my own environment. 

For easier access to another person's inbox, maybe try looking at the impersonation example, and seeing if that applies? If it doesn't, you can fetch the FolderId of their Calendar through the GetFolder operations, and getting the ID from it, and then set the Calendar to use that FolderId for all operations. This might make for cleaner, more maintainable code if you're doing multiple calls against a users calendar (or inbox, contacts, etc.)

Thanks for this comment
