### ISSUE TITLE
Composer not detecting the right library?

### ISSUE THREAD

**Issue by perskes** [Garethp/php-ews#68]
Hey, I saw your post in stackoverflow and I wanted to try your software to access calendar data of my outlook account on the exchange server.

I set everything up via composer, thanks to your reply in that [thread](http://stackoverflow.com/questions/37373516/getting-php-ews-to-work), but I encountered this message

`PHP Fatal error:  Class 'API' not found in /var/www/html/php-ews/demo.php on line 5``

with the code below.
It seems that it does not quite connect to your library, but why?
`vendor/autload.php` is the correct path to the autoload file.

`➜  php-ews git:(master) ✗ cat demo.php `
```php
<?php
require 'vendor/autoload.php';
use garethp\ews;

$client = API::withUsernameAndPassword(
    'mail.company.com',
    'u.sername',
    'secr3tpa55',
    [
        'httpPlayback' => [
            'mode' => 'live',
            'recordLocation' => __ROOT__ . DS . '/recordings.json'
        ]
    ]
);
?>

```

I assume that this is not the correct content of the autoload file, right?
`➜  php-ews git:(master) ✗ cat vendor/autoload.php `
```php
// autoload.php @generated by Composer

require_once __DIR__ . '/composer' . '/autoload_real.php';

return ComposerAutoloaderInitcb8cce25553426da4ff786df826fbf1c::getLoader();

```

I never used composer before, so it's quite a difficult thing to understand.

**Comment by Garethp** [comment]
Hi there

Can you try something for me? Can you change

```php
use garethp\ews;
```

to 

```php
use garethp\ews\API;
```

What it *looks* like is happening here is that you're importing the `garethp/ews` **namespace** when in this case you want the class itself. The difference here is that when you import a namespace, you still need to use the namespace when referring to a class. For an example, take a look [at this example code](https://github.com/Garethp/php-ews/blob/master/examples/contacts/createContacts.php).

Notice we have `use garethp\ews\ContactsAPI as API;`, which allows us to do `$api = API::withUsernameAndPassword('server', 'username', 'password');`, but then we have `use \garethp\ews\API\Enumeration;` where we're importing the whole namespace so to refer to an individual class we do `Enumeration\EmailAddressKeyType::EMAIL_ADDRESS_1`.

As to your confusion with the composer autoloading, it handles autoloading in a number of ways as quickly as possible. So, instead of trying to do dynamic autoloading for every request, when you do an `install`, `update` or `dump-autoload` it looks at your `composer.lock` file and generates a bunch of PHP classes then and there to do the autoloading. That's what all of the files in `vendor/composer` are for. It keeps `vendor/autoload.php` there so that it's easy to include, but it generates more PHP files in the background to speed things up for usage

**Comment by perskes** [comment]
Hey, I'm amazed by your detailed answer, which i really appreciate! Thank you for that!

Your Answer solved my problem, but I also have another Problem I can't really find out how to solve..

```➜  php-ews git:(master) ✗ php demo.php          
PHP Notice:  Use of undefined constant __ROOT__ - assumed '__ROOT__' in /var/www/html/php-ews/demo.php on line 12
PHP Notice:  Use of undefined constant DS - assumed 'DS' in /var/www/html/php-ews/demo.php on line 12
PHP Warning:  file_put_contents(__ROOT__DS/recordings.json/saveState.json): failed to open stream: Permission denied in /var/www/html/php-ews/vendor/garethp/http-playback/src/Client.php on line 189

➜  php-ews git:(master) ✗ sudo php demo.php     
PHP Notice:  Use of undefined constant __ROOT__ - assumed '__ROOT__' in /var/www/html/php-ews/demo.php on line 12
PHP Notice:  Use of undefined constant DS - assumed 'DS' in /var/www/html/php-ews/demo.php on line 12

```

PHP Version:
➜  php-ews git:(master) ✗ php -v
PHP 5.6.26-0+deb8u1 (cli) (built: Oct  7 2016 08:34:14) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copy wright (c) 1999-2016, by Zend Technologies


That's what the file did on execution:

It created a folder call __ROOT__DS/ and saved the result of the failed call..
```
➜  php-ews git:(master) ✗ cat  __ROOT__DS/recordings.json/saveState.json 
[]%                                                                                                                                                                    ➜  php-ews git:(master) ✗ 

```

Any idea? Thank you :)

**Comment by Garethp** [comment]
Well, quite obviously you haven't defined `__ROOT__` or `DS`. The error that you're getting is that you're trying to use constants that aren't defined, so it just uses the name of the constant as the value. Hence why it creates a folder called `__ROOT__DS`. If you want to save the value of the calls to a certain place, set the following line

`'recordLocation' => './recordings/'`

Or define the constants like this

```php
define('__ROOT__', './recordings');
define('DS', DIRECTORY_SEPARATOR);
```

above where you try to instantiate the API class.

However, you don't need to use the HttpPlayback settings unless you're either writing tests or I ask for the recordings for debugging

**Comment by perskes** [comment]
Hey, thanks! I get it.. php is not my first language, I just assumed it's some sort of unique-to-php piece.

I read a bit more about your work and found the examples pages.
I took this one https://github.com/Garethp/php-ews/blob/master/examples/calendar/getCalendarItems.php
And have it a try, but I get a curl error.

It can't access https sites it seems. I know when I used curl from terminal, that there is a parameter to pass to ignore ssl checks, is there an implementation in your library for that?

Just to double check, here's the code:


```
require 'vendor/autoload.php';
use garethp\ews\API;

$server = 'https://mail.company.tld';
$username = 'personaluser';
$password = 'supersecret';

$api = API::withUsernameAndPassword('server', 'username', 'password');
$calendar = $api->getCalendar();

//Get all items from midday today
$items = $calendar->getCalendarItems('12:00 PM');

//Get all items from 8 AM to 9 AM today
$start = new DateTime('8:00 AM');
$end = new DateTime('9:00 AM');
$items = $calendar->getCalendarItems($start, $end);

//Get a list of items in a Date Range
$items = $calendar->getCalendarItems('31/05/2015', '31/06/2015');

foreach ($items as $item) {
    $subject = $item->getSubject();

```

And the Error:

```
PHP Fatal error:  Uncaught exception 'GuzzleHttp\Exception\ConnectException' with message 'cURL error 6: Could not resolve host: server (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in /var/www/html/php-ews/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:186
Stack trace:
#0 /var/www/html/php-ews/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array)
#1 /var/www/html/php-ews/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#2 /var/www/html/php-ews/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory))
#3 /var/www/html/php-ews/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\ in /var/www/html/php-ews/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 186

```

**Comment by Garethp** [comment]
You actually need to enter the value for `'server'`. It's complaining because you passed in `'server'` as the url to query. And it couldn't resolve the host `server`. Try this instead

`$api = API::withUsernameAndPassword($server, $username, $password);`

**Comment by perskes** [comment]
Aaaah! I'm feeling so stupid about not noticing the high-comma. I overlooked it and thought it's a call for the variables.

So, I did that now, and I get an error pointing out an uncaught exception occured. Apparently it is originally called by an 401 error, which means unauthorized.

my server is webmail.company.com
may user is u.sername (without the @company.com)
and my regular password.
webmail.company.com/EWS/Exchange.asmx can be called, so I assume that EWS is running.

What else could cause an authorization error?
```

PHP Fatal error:  Uncaught exception 'garethp\ews\API\Exception\UnauthorizedException' in /var/www/html/php-ews/vendor/garethp/php-ews/src/API/ExchangeWebServices.php:439
Stack trace:
#0 /var/www/html/php-ews/vendor/garethp/php-ews/src/API/ExchangeWebServices.php(354): garethp\ews\API\ExchangeWebServices->handleNonSuccessfulResponses(NULL, 401)
#1 /var/www/html/php-ews/vendor/garethp/php-ews/src/API/ExchangeWebServices/MiddlewareFactory.php(57): garethp\ews\API\ExchangeWebServices->processResponse(NULL)
#2 /var/www/html/php-ews/vendor/garethp/php-ews/src/API/ExchangeWebServices.php(498): garethp\ews\API\ExchangeWebServices->garethp\ews\API\ExchangeWebServices\{closure}(Object(garethp\ews\API\MiddlewareRequest), Object(Closure))
#3 /var/www/html/php-ews/vendor/garethp/php-ews/src/API/ExchangeWebServices/MiddlewareFactory.php(66): garethp\ews\API\ExchangeWebServices->garethp\ews\API\{closure}(Object(garethp\ews\API\MiddlewareRequest))
#4 /var/www/html/php-ews/vendor/garethp/php-ews/src/API/ExchangeWebServices.php(498): garethp\e in /var/www/html/php-ews/vendor/garethp/php-ews/src/API/ExchangeWebServices.php on line 439

```

Do I have to change some settings on my Exchange Server, like a certain User that is allowed to use the EWS?

**Comment by Garethp** [comment]
Can you try it with the `@company.com`?

**Comment by perskes** [comment]
Hi, I schould have mentioned that I tried multiple comibinations.

mail.company.com
u.name@company.com
password

Fails with the above error

mail.company.com
u.name
password

fails the same way

https://mail.company.com
u.name@company.com
password

Fails as well.

I had an umlaut in my password, which I changed now and I tried it again, but no luck.
my password contains letters, symbols and numbers, like this#123, but the #-symbol shouldn't cause errors. I removed the umlaut because It made trouble with my ldap connection before (then I switched to ldao v3).

now.. without the umlaut and the @company.com
mail.company.com, u.name, passwordwithoutumlaut
it gives me this:

```
PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTime::__construct(): Failed to parse time string (31/05/2015) at position 0 (3): Unexpected character' in /var/www/html/php-ews/vendor/garethp/php-ews/src/CalendarAPI.php:112
Stack trace:
#0 /var/www/html/php-ews/vendor/garethp/php-ews/src/CalendarAPI.php(112): DateTime->__construct('31/05/2015')
#1 /var/www/html/php-ews/demo.php(19): garethp\ews\CalendarAPI->getCalendarItems('31/05/2015', '31/06/2015')
#2 {main}
  thrown in /var/www/html/php-ews/vendor/garethp/php-ews/src/CalendarAPI.php on line 112

```

With umlaut I get the same error as previously posted. Are umlauts supported?

I got it working without umlauts, but I'd like to have umlauts (and not permit any user to set a password with umlauts..)


What I also don't get ist, why this timerange does not work properly.
$items = $calendar->getCalendarItems('01/10/2016', '30/10/2016');

PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTime::__construct(): Failed to parse time string (30/10/2016) at position 0 (3): Unexpected character' in /var/www/html/php-ews/vendor/garethp/php-ews/src/CalendarAPI.php:116

Fixed it. I had to use 01.10.2016...is it based on the locales?

Thanks a lot for you support and the time you put into this!
Now I just have to figure out how to get the label (if possible), the start and end-time of the appointment and the body, but I'm confident I'll find that in your documentation! :+1:

**Comment by Garethp** [comment]
Now, those are some interesting errors. Regarding umlaut support, I can't really tell you where that error is coming from, but I'll investigate in to the issue to see if I can reproduce it. I'm not doing anything special with the password string, it should be passed straight in to curl as an NTLM or Basic authentication. If there's an error there, it'll be either in a library that I'm using for calls, in the php cURL library, in cURL itself or something to do with Exchange. I'll look in to that.

As to the range `$items = $calendar->getCalendarItems('01/10/2016', '30/10/2016');` not working, could you try formatting it as `2016-10-01` instead? It looks like you're right, it probably is the locale. I tested that date in php in my shell, and it seems that the php [`DateTime`](http://php.net/manual/en/class.datetime.php) object automatically assumes an American format. Weird, but I never caught it as I usually use `2016-10-30` instead. So, in your example, it thought you were using an American format and then couldn't parse the date, since it thought `30` referred to the month, not the day. Weird, I know, but Americans...

I don't have any documentation for labels, but fetching the Start Time, End Time and Body should be easy enough. I highly recommend using `PhpStorm` as your IDE, as it will give you very helpful hints as to what methods are available for using on an object. You *may* have to do an individual `getItem` on the calendar item before you get the object for actually really interesting reasons that I researched and did a write-up on [here](http://stackoverflow.com/questions/34426828/php-ews-why-isnt-a-calendar-events-body-a-accessible-from-an-event-just-like).

I'm happy I was able to help, and I hope my documentation does help as well. It's a bit sparse, but to be honest it doesn't document **how to interact with Exchange**, only how to use this library. That's because this library really only wraps around SOAP to provide easier usages. If you look inside the code for the methods like `getCalendarItems` or `getItem`, you'll see that they just pass an array down to a a method. The methods are public, and the arrays just get transformed in to XML directly. So, if you need to do something that this library doesn't support, just look for documentation on the Exchange Web Services directly, and try to run that with my library.

For a really good example, compare the code in the [`convertIdFormat()`](https://github.com/Garethp/php-ews/blob/master/src/API.php#L480) method with the structure of the XML used as an example in the [EWS Article on Converting Id Formats](https://msdn.microsoft.com/en-us/library/office/bb799665(v=exchg.150).aspx). Notice the Array basically matches the XML one to one.

There are a lot of areas where my library steps in to simplify what you have to write to talk to Exchange (Magic Properties, Simplifying Responses, Handling Authentication, Middleware etc...), but I don't have much documentation on how to do something with Exchange because Exchange itself is a great source of documentation

**Comment by perskes** [comment]
Actually I use nano directly on the server, I used brackets.io for the creation of the tool and now I only make rudimentary changes, so nano is quite acceptable. I'll definitely check out phpstorm for further development! Thanks! 

I can query everything I need besides the label, the ID and the body with this code:
```
<?php

require 'vendor/autoload.php';
use garethp\ews\API;


$api = API::withUsernameAndPassword('mail.xxx.at', 's.xxx', 'xxxxx#123');
$calendar = $api->getCalendar();

//Get all items from midday today
//$items = $calendar->getCalendarItems('01:00 AM');

//Get all items from 8 AM to 9 AM today
//$start = new DateTime('01:00 AM');
//$end = new DateTime('11:00 PM');
//$items = $calendar->getCalendarItems($start, $end);

//Get a list of items in a Date Range
$items = $calendar->getCalendarItems('10.10.2016', '20.10.2016');

foreach ($items as $item) {
    $subject = $item->getSubject();
    $start = $item->getStart();
    $end = $item->getEnd();
    $location = $item->getLocation();

echo $subject . "\n";
echo $start . "\n";
echo $end . "\n";
echo $location . "\n";
}
?>

```

When I try to query the ID of the event, I get a null error as mentioned here: https://github.com/Garethp/php-ews/issues/9

So I used the brackets () to call the function in  correct manner, but then it stays empty.

```
$itemID = $item->getItemId();
echo $itemID . "\n";
```

So, since this is empty, I can't iterate (?) through the events to get the body, besides that I don't know how to iterate through the events to get their body. I'd like to post a working code to your examples so others can benefit from it, but I'm afraid I'm too much of a novice to do so.

How do I call the getItemId() function properly to give me the ID of the event?
And do you have any source on looping through the events to get their body?
I saw your post here: http://stackoverflow.com/questions/34426828/php-ews-why-isnt-a-calendar-events-body-a-accessible-from-an-event-just-like
and I understand the reason why the body is not easily accessible like the subject for example, but I can only seccond what the OP said, I'd would be a great thing.

Thank you for your detailed answers, they are very enlightening, even for a novice like me!
Big thanks for the work with the wrapper making peoples life easier!

**Comment by Garethp** [comment]
An `ItemId` actually consists of two things: And `Id` and a `ChangeKey`. This way if you get an Item, try to update it but it's already been changed in the period where you fetched it and when you tried to change it, the server can reject the change. So when you do `getItemId()`, you're actually getting an object, [`ItemIdType`](https://github.com/Garethp/php-ews/blob/master/src/API/Type/ItemIdType.php). If you actually wanted to get the Id itself, as a string, you would do `$item = $item->getItemId()->getId()`. But, to get an item individually, you don't need to do that. You can simply do

```php
$item = $api->getItem($item->getItemId());
```

The function will accept the `ItemIdType` object directly. Likewise, once you have the item, trying to get the body will also return an object, the [`BodyType`](https://github.com/Garethp/php-ews/blob/master/src/API/Type/BodyType.php) object. This is where my library comes in a little handy, you should still be able to use it as a string. But, to be on the safe side, I'd suggest [`type-casting`](http://php.net/manual/en/language.types.type-juggling.php), it so that you don't have to worry about thinking the value is a string, but it's actually not. So, for instance:

```php
$item = $api->getItem($item->getItemId());
$body = (string) $item->getBody();
```

For future reference, I'd suggest instead of trying to inspect the value of the variable with `echo`, try `print_r`, it'll tell you the type of the value as well as dig in to the values of the properties of the objects. I suggest doing it for trying to figure out how to get the Categories (But I'd start with `$item->getCategories()`).

If you see a property, the objects automatically have getters for them (So `$item->body` is the property, it automatically has `$item->getBody()`), so that's how you'll access the properties you see

**Comment by perskes** [comment]
Hey man, thanks a lot for your support, again! 
I came back to close the ticket and tell you I was succsessful with all my data-query stuff!
I hope I can help you a bit with the umlauts problem! See you over there!
