### ISSUE TITLE
Problems with DateTime: Uncaught exception 'Exception' with message 'DateTime::__construct()

### ISSUE THREAD

**Issue by robp2175** [Garethp/php-ews#90]
So, I am having problems with both yours and JamesIArmes php-ews regarding DateTime and I have no idea why. I wrote an issue on James Github, but he appears to be taking a break from the project right now. 
I am on PHP 5.6.30 and CentOS Linux release 7.3.1611. 

I would greatly appreciate any assistance your or others users could provide. Thank You.

I used your getCalendarItems.php example, but I just keep getting this error below when I use your fork. Obviously I put in my credentials and server, but otherwise used the example exactly as written just to test.

`[Tue Apr 25 08:35:51.236654 2017] [:error] [pid 15146] [client 10.40.2.23:57090] PHP Fatal error:  Uncaught exception 'Exception' with message 'DateTime::__construct(): Failed to parse time string (31/04/2017) at position 0 (3): Unexpected character' in /var/www/html/glpimaintenance/form/vendor/garethp/php-ews/src/CalendarAPI.php:112\nStack trace:\n#0 /var/www/html/glpimaintenance/form/vendor/garethp/php-ews/src/CalendarAPI.php(112): DateTime->__construct('31/04/2017')\n#1 /var/www/html/glpimaintenance/form/ews3.php(13): garethp\\ews\\CalendarAPI->getCalendarItems('31/04/2017', '31/06/2017')\n#2 {main}\n  thrown in /var/www/html/glpimaintenance/form/vendor/garethp/php-ews/src/CalendarAPI.php on line 112`

When I use James fork using his example: https://github.com/jamesiarmes/php-ews/blob/master/examples/user/meeting-suggestions.php, I get the error below just using his example as is (of course putting in my credentials, server, etc.)

```
$start = new DateTime('next wednesday 00:00:00');
$end = new DateTime('next thursday 00:00:00');

[Wed Apr 26 07:09:55.018472 2017] [:error] [pid 19994] [client 10.40.2.23:63064] PHP Fatal error:  Uncaught SoapFault exception: [a:ErrorSchemaValidation] The request failed schema validation: The 'http://schemas.microsoft.com/exchange/services/2006/types:StartTime' element is invalid - The value '2017-04-28' is invalid according to its datatype 'http://www.w3.org/2001/XMLSchema:dateTime' - The string '2017-04-28' is not a valid DateTime value. in /var/www/html/glpimaintenance/form/vendor/php-ews/php-ews/src/Client.php:1631\nStack trace:\n#0 /var/www/html/glpimaintenance/form/vendor/php-ews/php-ews/src/Client.php(1631): SoapClient->__call('GetUserAvailabi...', Array)\n#1 /var/www/html/glpimaintenance/form/vendor/php-ews/php-ews/src/Client.php(1631): jamesiarmes\\PhpNtlm\\SoapClient->GetUserAvailability(Object(jamesiarmes\\PhpEws\\Request\\GetUserAvailabilityRequestType))\n#2 /var/www/html/glpimaintenance/form/vendor/php-ews/php-ews/src/Client.php(1126): jamesiarmes\\PhpEws\\Client->makeRequest('GetUserAvailabi...', Object(jamesiarmes\\PhpEws\\Request\\GetUserAvailabilityRequestType))\n#3 /var/www/html/glpimaintenance/for in /var/www/html/glpimaintenance/form/vendor/php-ews/php-ews/src/Client.php on line 1631

```

**Comment by Garethp** [comment]
Could you please show me the code you've got with my branch?

**Comment by robp2175** [comment]
require_once 'vendor/autoload.php';

```
use garethp\ews\API;
$api = API::withUsernameAndPassword('exchange', 'myuser', 'mypass');
$calendar = $api->getCalendar();
//Get all items from midday today
$items = $calendar->getCalendarItems('12:00 PM');
echo $items;
//Get all items from 8 AM to 9 AM today
$start = new DateTime('8:00 AM');
$end = new DateTime('9:00 AM');
$items = $calendar->getCalendarItems($start, $end);
echo $items;
//Get a list of items in a Date Range
$items = $calendar->getCalendarItems('31/04/2017', '31/05/2017');

```

**Comment by Garethp** [comment]
It seems like PHP's `DateTime` class really really hates that format of date. Try changing it to `YYY-mm-dd` format instead, and it should work

**Comment by robp2175** [comment]
Thanks I was able to get it to work by changing the format. I am not sure why the other format was presenting a problem. Very odd.

Still can't get James' to work, very weird.

**Comment by Garethp** [comment]
Looking in to it, it looks like \DateTime automatically tries to parse it in American date format for some stupid reason. So it thinks the `31` is the month, which causes an error

**Comment by robp2175** [comment]
This is very strange, why aren't others having this problem? Honestly, I was really hoping to use James version because he has some built in stuff to get user availability, but the same fix is still not working on his, very odd.  I am thinking I can do the same thing using impersonation using your Fork, which is also excellent BTW, thank you for your work on it.

I have a couple of questions, and if this is not the correct place, please let me know.
1. What is the best way to to iterate through this object? I am new to objects in php and they seem to work very different than a typical array.
$items = $calendar->getCalendarItems('31/04/2017', '31/05/2017');

2. What I am trying to do is very simple. I want to look at another users calendar (in this case, it would actually be a resource calendar), to determine if the room/user is available during a particular timeframe. It only needs to return a true/false answer. What do you think would be the best way to do this using your fork?

I appreciate your time and your efforts.

**Comment by Garethp** [comment]
> This is very strange, why aren't others having this problem?

I think I've fielded this question before actually. If other people encountered it, they probably just changed the format. It's a an error caused by core PHP. If you want, you can also pass in a `DateTime` object instead of a string, if you want to be specific.

> Honestly, I was really hoping to use James version because he has some built in stuff to get user availability

What does his have? If his has something that I'm missing, I'll try to add it

> but the same fix is still not working on his

Hm... maybe instead of passing in a simple format like that, try something like `(new DateTime($dateString))->foramt('c');`. I know that Exchange expects the DateTime in a specific, long format, and my library autoconverts for you while Jame's doesn't

> What is the best way to to iterate through this object? I am new to objects in php and they seem to work very different than a typical array.

Usually, objects are different. However, I've had the [object](https://github.com/Garethp/php-ews/blob/master/src/API/Type/FindItemParentType.php) implement certain Interfaces ([`Countable`](http://php.net/manual/en/class.countable.php), [`ArrayAccess`](http://php.net/manual/en/class.arrayaccess.php) and [`IteratorAggregate`](http://php.net/manual/en/class.iteratoraggregate.php)) that allows you to traverse them as if they were an array. You can even do `count()` on them if you want. So you should just be able to do

```php
$items = $items = $calendar->getCalendarItems('31/04/2017', '31/05/2017');
foreach ($item as $item) {
}
```

> What I am trying to do is very simple. I want to look at another users calendar (in this case, it would actually be a resource calendar), to determine if the room/user is available during a particular timeframe. It only needs to return a true/false answer. What do you think would be the best way to do this using your fork?

So, this is an interesting question. I'd suggest you want to be looking at the [GetUserAvailability](https://msdn.microsoft.com/en-us/library/office/hh532567(v=exchg.80).aspx) function of EWS. The example there is for their own C# library, but it shows the XML request/responses, you'll want to use that as your how to.

Essentially, all my and jame's API does is make it easier to communicate with the XML. I have very nice methods like `getCalendarItems`, but if you look at the code inside it (And I recommend you do, I try to keep it nice and clean and easy to reference), you'll see that all it does is create an array and pass it further down.

That's basically the core of my library. It takes an array, converts it to an object, and uses that object to talk to the SOAP server, and get the object back. So if I don't have a method that makes it simple to do this call, simply try to build an array similar to the XML and pass it down. It's documented as part of the [Manual Usage](https://github.com/Garethp/php-ews#manual-usage) section of my README, as well as in my example, [`building requests`](https://github.com/Garethp/php-ews/blob/master/examples/basic/buildingRequests.php).

I can't tell you exactly how to do it right now, though I might try to add it in the next couple of weeks, but hopefully that can give you a starting point.

**Comment by robp2175** [comment]
Perfect, I got done what I needed. Thanks for the assistance.

**Comment by Garethp** [comment]
What was the code you ended up with?

**Comment by robp2175** [comment]
This is extremely ugly right now, it still needs a lot of work, but it will get the job done. 

```
<?php
require_once 'vendor/autoload.php';

use garethp\ews\API;
use garethp\ews\API\Enumeration;
use garethp\ews\API\Type;
$api = API::withUsernameAndPassword('exchange', 'admin', 'admin',
    ['impersonation' => 'mh-225@mydomain.edu']
);
$calendar = $api->getCalendar();
//Get all items from midday today
//$items = $calendar->getCalendarItems('12:00 PM');
//echo $items;
//Get all items from 8 AM to 9 AM today
//$start = new DateTime('8:00 AM');
//$end = new DateTime('9:00 AM');
//$items = $calendar->getCalendarItems($start, $end);
//Get a list of items in a Date Range
$items = $calendar->getCalendarItems('27-04-2017 8:30', '9-06-2017 19:00');
$c = count($items);

if ( $c == 0 ) {
    echo "There are no apoointments during this time";
    exit;
} else {
    echo "There are conflicting events during this time";

    foreach ($items as $item) {
       $subject = $item->getSubject();
       echo "<br />";
       $start = $item->getStart();
       $end = $item->getEnd();
       echo $item->getItemId()->getId();
       echo $subject;
       echo "<br />";
       echo date("m-d-Y h:s", strtotime($start));
       echo "<br />";
       echo date("m-d-Y h:s", strtotime($end));
       echo "<br />";
       echo "<br />";
    }

//echo "<pre>";
//var_dump($items);
//echo "</pre>";
}

```

**Comment by Garethp** [comment]
I'd suggest following #91, I'll add something to make this easier, as well as some examples, in the coming week

**Comment by Garethp** [comment]
FYI, I've added a function that should make this easier for you https://github.com/Garethp/php-ews/blob/master/examples/calendar/checkingIfUsersAreFree.php
